version: "2"

services:
  gen:
    build: gen
    ports:
    - "8001:80"

  hashr:
    build: Hashr
    ports:
    - "8002:80"

  ui:
    build: ui
    ports:
    - "8000:80"
    links:
    - store

  store:
    build: store
    ports:
    - "8003:80"

  worker:
    build: worker
    links:
     - hashr
     - gen
     - store